### ISSUE TITLE
Cheker reset

### ISSUE THREAD

**Issue by Aleck85** [Vinne2/fbnotifier-for-chrome#2]
When I only go to FB, the icon cheсker always reset, regardless if I have read (message, notification etc), or no. It is very uncomfortable. 

![default](https://cloud.githubusercontent.com/assets/5072865/14636902/d90d1346-0636-11e6-8c53-0b53ca9edddb.JPG)

**Comment by Kaligula0** [comment]
Yes. Because when you go to FB you already see the number of notifications THERE – so the button is then unnecessary. But still it refreshes after a certain interval which you can set in settings.

**Comment by Kaligula0** [comment]
You've described what situation is now. The reset of counter when visiting FB is intentional. But what behavior would you like to see instead? You didn't say.

**Comment by Aleck85** [comment]
I would like to count on the icon showing the number of messages and notifications as long as I did not mark them as read.

**Comment by Kaligula0** [comment]
You can still set any shorter refresh interval so that the extension checks more frequently :)

But, well, let's take a look at your issue. You want behavior like below? ↓
- you open browser - see red "5" on button
- you click button - see red "5" on button
- you read first one - see red "4" on button
- you read second one - see red "3" on button
- you read third one - see red "2" on button
- and so on…

If this is what you want then my answer is: no.

This would require instant communications between FB and the extension. Or even push notifications. That would require logging in to FB inside extension (the extension would know your login and password). And that would increase web traffic. That would result in the extension not being that simple. And that would use more RAM – which is completely totally opposite of what this was made for :)

**Comment by Kaligula0** [comment]
To minimize the use of RAM and web traffic extension periodically requests (opens) a very very lite (well, the lightest) mobile version of the lightest FB page and extracts number of notifications. This is the simplest method among those which don't require giving the extension any permissions to your account.

**Comment by Aleck85** [comment]
I just want to see 5 until the next refreshing (like in some gmail extensions). For example this one (https://chrome.google.com/webstore/detail/inbox-by-gmail-checker/mpjmeeikbbgccbjkbfabocnjcaejdpmj?utm_source=chrome-app-launcher-info-dialog) dont require logging into gmail account inside extension.

**Comment by Kaligula0** [comment]
What is the difference between when you have 5 unread notifications and click the button to open FB and then:
- the button counter vanishes (until next refresh), but you have FB page opened and see the notifications, moreover, probably huge most of the users open FB to check all the notifications; whats more if you're still on FB and didn't open all notifcations, eventually the button refreshes and shows\* the number of unread notifications
- the button counter still says 5, and you read notifications, read some of them, the counter still says 5, and then after some time the counter refreshes and shows\* new unread value
  ?
  In any of these cases you cannot rely on button counter to know what is the true numer of notifications – until next refresh. The same situation is when you open FB manually – the button won't show actual unread value until next refresh. Between two refreshes the button is unreliable if you read any notification.
  Please, convince me.
  ;)
  _____
  *) probably; it depends on if you clicked to open the notifications/msgs list or not

**Comment by Aleck85** [comment]
If I read 4 of 5 notifications and then close the fb tab, will I see 1 after next refreshing? That's what I want.
